#############################################################################
# Generated by PAGE version 4.25.1
#  in conjunction with Tcl version 8.6
#  Dec 15, 2022 12:09:19 PM CET  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}



    menu .pop47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) \
        -font $vTcl(actual_gui_font_menu_desc) -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop47" "Popupmenu1" vTcl:WidgetProc "" 1
    menu .pop48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(pr,menubgcolor) \
        -font $vTcl(actual_gui_font_menu_desc) -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop48" "Popupmenu2" vTcl:WidgetProc "" 1

proc vTclWindow.top37 {base} {
    global vTcl
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 657x655+302+131
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1684 1032
    wm minsize $top 148 10
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "GUI" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list disabled $vTcl(actual_gui_bg) selected $vTcl(pr,guicomplement_color)]
    ttk::notebook $top.tNo38 \
        -width 619 -height 561 -takefocus {} 
    vTcl:DefineAlias "$top.tNo38" "TNotebook1" vTcl:WidgetProc "GUI" 1
    frame $top.tNo38.pg0 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo38.pg0" "TNotebook1_t0" vTcl:WidgetProc "GUI" 1
    $top.tNo38 add $top.tNo38.pg0 \
        -padding 0 -sticky nsew -state normal -text Seriale -image {} \
        -compound none -underline -1 
    set site_4_0  $top.tNo38.pg0
    button $site_4_0.but45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Usa questa} 
    vTcl:DefineAlias "$site_4_0.but45" "Button1" vTcl:WidgetProc "GUI" 1
    button $site_4_0.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Riprova 
    vTcl:DefineAlias "$site_4_0.but46" "Button2" vTcl:WidgetProc "GUI" 1
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_4_0.scr47 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_0.scr47" "Scrolledlistbox1" vTcl:WidgetProc "GUI" 1

    $site_4_0.scr47.01 configure -background white \
        -disabledforeground #a3a3a3 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    place $site_4_0.but45 \
        -in $site_4_0 -x 65 -y 340 -width 170 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_4_0.but46 \
        -in $site_4_0 -x 330 -y 340 -width 170 -height 40 -anchor nw \
        -bordermode ignore 
    place $site_4_0.scr47 \
        -in $site_4_0 -x 45 -y 45 -width 511 -height 255 -anchor nw \
        -bordermode ignore 
    frame $top.tNo38.t0 \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo38.t0" "TNotebook1_t1" vTcl:WidgetProc "GUI" 1
    $top.tNo38 add $top.tNo38.t0 \
        -padding 0 -sticky nsew -state normal -text Varie -image {} \
        -compound none -underline -1 
    set site_4_1  $top.tNo38.t0
    button $site_4_1.but43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Eco 
    vTcl:DefineAlias "$site_4_1.but43" "Button3" vTcl:WidgetProc "GUI" 1
    labelframe $site_4_1.lab44 \
        -font TkDefaultFont -foreground black -text Prova \
        -background $vTcl(actual_gui_bg) -height 164 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 230 
    vTcl:DefineAlias "$site_4_1.lab44" "TLabelframe1" vTcl:WidgetProc "GUI" 1
    set site_5_0 $site_4_1.lab44
    label $site_5_0.lab39 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Invia 
    vTcl:DefineAlias "$site_5_0.lab39" "Label2" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent40 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable numEco 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry2" vTcl:WidgetProc "GUI" 1
    button $site_5_0.but41 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Eco 
    vTcl:DefineAlias "$site_5_0.but41" "Button4" vTcl:WidgetProc "GUI" 1
    ttk::progressbar $site_5_0.tPr43 \
        -mode indeterminate 
    vTcl:DefineAlias "$site_5_0.tPr43" "TProgressbar1" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab37 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text da 
    vTcl:DefineAlias "$site_5_0.lab37" "Label8" vTcl:WidgetProc "GUI" 1
    entry $site_5_0.ent38 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -justify center -selectbackground #c4c4c4 \
        -selectforeground black -textvariable dimEco 
    vTcl:DefineAlias "$site_5_0.ent38" "Entry10" vTcl:WidgetProc "GUI" 1
    label $site_5_0.lab40 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text bytes 
    vTcl:DefineAlias "$site_5_0.lab40" "Label9" vTcl:WidgetProc "GUI" 1
    place $site_5_0.lab39 \
        -in $site_5_0 -x 20 -y 25 -width 39 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.ent40 \
        -in $site_5_0 -x 75 -y 25 -width 69 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.but41 \
        -in $site_5_0 -x 160 -y 25 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.tPr43 \
        -in $site_5_0 -x 27 -y 112 -width 180 -height 22 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab37 \
        -in $site_5_0 -x 42 -y 75 -anchor nw -bordermode ignore 
    place $site_5_0.ent38 \
        -in $site_5_0 -x 77 -y 74 -width 60 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_5_0.lab40 \
        -in $site_5_0 -x 162 -y 78 -anchor nw -bordermode ignore 
    place $site_4_1.but43 \
        -in $site_4_1 -x 48 -y 44 -width 50 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_1.lab44 \
        -in $site_4_1 -x 155 -y 40 -width 230 -height 164 -anchor nw \
        -bordermode ignore 
    label $top.lab39 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -textvariable Messaggio 
    vTcl:DefineAlias "$top.lab39" "Label1" vTcl:WidgetProc "GUI" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo38 \
        -in $top -x 15 -y 65 -width 619 -relwidth 0 -height 561 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab39 \
        -in $top -x 25 -y 15 -width 600 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top37 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

